server:
  port: 80
#  context-path: /web
eureka:
  client:
    serviceUrl:
#       defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://39.106.58.46:8761/eureka/
spring:
  application:
    name: pc-web
